// For GET_USER_SUBSCRIPTION_REQUEST
export const GET_USER_SUBSCRIPTION_REQUEST = "GET_USER_SUBSCRIPTION_REQUEST";
export const GET_USER_SUBSCRIPTION_SUCCESS = "GET_USER_SUBSCRIPTION_SUCCESS";
export const GET_USER_SUBSCRIPTION_FAILURE = "GET_USER_SUBSCRIPTION_FAILURE";

// For UPGRADEUSER_SUBSCRIPTION_REQUEST
export const UPGRADEUSER_SUBSCRIPTION_REQUEST = "UPGRADEUSER_SUBSCRIPTION_REQUEST";
export const UPGRADEUSER_SUBSCRIPTION_SUCCESS = "UPGRADEUSER_SUBSCRIPTION_SUCCESS";
export const UPGRADEUSER_SUBSCRIPTION_FAILURE = "UPGRADEUSER_SUBSCRIPTION_FAILURE";
