// For FETCH_ISSUES_REQUEST
export const FETCH_ISSUES_REQUEST = "FETCH_ISSUES_REQUEST";
export const FETCH_ISSUES_SUCCESS = "FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_FAILURE = "FETCH_ISSUES_FAILURE";

// For FETCH_ISSUES_BY_ID_REQUEST
export const FETCH_ISSUES_BY_ID_REQUEST = "FETCH_ISSUES_BY_ID_REQUEST";
export const FETCH_ISSUES_BY_ID_SUCCESS = "FETCH_ISSUES_BY_ID_SUCCESS";
export const FETCH_ISSUES_BY_ID_FAILURE = "FETCH_ISSUES_BY_ID_FAILURE";

// For CREATE_ISSUES_REQUEST
export const CREATE_ISSUES_REQUEST = "CREATE_ISSUES_REQUEST";
export const CREATE_ISSUES_SUCCESS = "CREATE_ISSUES_SUCCESS";
export const CREATE_ISSUES_FAILURE = "CREATE_ISSUES_FAILURE";

// For DELETE
export const DELETE_ISSUES_REQUEST = "DELETE_ISSUES_REQUEST";
export const DELETE_ISSUES_SUCCESS = "DELETE_ISSUES_SUCCESS";
export const DELETE_ISSUES_FAILURE = "DELETE_ISSUES_FAILURE";

// For UPDATE_ISSUES_STATUS_REQUEST
export const UPDATE_ISSUES_STATUS_REQUEST = "UPDATE_ISSUES_STATUS_REQUEST";
export const UPDATE_ISSUES_STATUS_SUCCESS = "UPDATE_ISSUES_STATUS_SUCCESS";
export const UPDATE_ISSUES_STATUS_FAILURE = "UPDATE_ISSUES_STATUS_FAILURE";


// For ASSIGNED_ISSUE_TO_USER_REQUEST
export const ASSIGNED_ISSUE_TO_USER_REQUEST = "ASSIGNED_ISSUE_TO_USER_REQUEST";
export const ASSIGNED_ISSUE_TO_USER_SUCCESS = "ASSIGNED_ISSUE_TO_USER_SUCCESS";
export const ASSIGNED_ISSUE_TO_USER_FAILURE = "ASSIGNED_ISSUE_TO_USER_FAILURE";
